### ISSUE TITLE
Cannot read properties of undefined (reading 'getUserForContext')

### ISSUE THREAD

**Issue by devbaraus** [StouderIO/adonis-auditing#22]
```json
err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'getUserForContext')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'getUserForContext')
              at Proxy.$audit (file:///home/devbaraus/labbaraus/qurvo-server/node_modules/@stouder-io/adonis-auditing/build/index.js:133:49)
              at ModelWithAudit.afterSaveHook (file:///home/devbaraus/labbaraus/qurvo-server/node_modules/@stouder-io/adonis-auditing/build/index.js:151:30)
              at Runner.#exec (/home/devbaraus/labbaraus/qurvo-server/node_modules/@poppinss/hooks/src/runner.ts:119:13)
              at Runner.run (/home/devbaraus/labbaraus/qurvo-server/node_modules/@poppinss/hooks/src/runner.ts:136:17)
              at Proxy.save (file:///home/devbaraus/labbaraus/qurvo-server/node_modules/@adonisjs/lucid/build/src/orm/base_model/index.js:1369:55)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async User.create (file:///home/devbaraus/labbaraus/qurvo-server/node_modules/@adonisjs/lucid/build/src/orm/base_model/index.js:438:9)
              at HTTPLoggerMiddleware.handle (/home/devbaraus/labbaraus/qurvo-server/app/middleware/http_logger_middleware.ts:67:5)
      "status": 500
    }
```

**Comment by jsilva74** [comment]
Hi.

I'm getting the same error in a seeder which attempts to create a user with User.updateOrCreate() or User.create() methods.

**Comment by Xstoudi** [comment]
Hey, I'd look into it. You have no other warning in console right?

**Comment by devbaraus** [comment]
> Hi.
> 
> I'm getting the same error in a seeder which attempts to create a user with User.updateOrCreate() or User.create() methods.
> 

Could you test if enabling asyncLocalStorage this error persists?

**Comment by jsilva74** [comment]
@devbaraus asyncLocalStorage was enabled when the error occurs.
